export const KEYWORD_RESEARCH_CATEGORIES = [
  "Dentist",
  "Restaurant",
  "Pub",
  "Bar",
  "SEO Agency",
  "Roofing Contractor",
  "Real Estate Agent",
  "Hair Salon",
  "Gym",
  "Plumber",
  "Electrician",
  "Lawyer",
  "Cafe",
  "Hotel",
  "Spa",
  "Auto Repair",
  "Bakery",
  "Pharmacy",
  "Veterinarian",
  "Accounting Firm",
] as const;

export const KEYWORD_RESEARCH_LOCATIONS = [
  "Chennai",
  "Bangalore",
  "Mumbai",
  "Coimbatore",
  "Madurai",
  "Hyderabad",
  "Delhi",
  "Pune",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Kochi",
  "New York",
  "Los Angeles",
  "Chicago",
  "London",
  "Toronto",
  "Sydney",
  "Dubai",
] as const;
