"use client";

import { useState } from "react";
import Link from "next/link";
import { Menu, X } from "lucide-react";
import { DocsProductProvider, useDocsProduct } from "./docs-product-context";
import { DocsLogo } from "./docs-logo";
import { DocsSidebar } from "./docs-sidebar";
import { DocsSearchTrigger } from "./docs-search";
import { DocsThemeProvider } from "./docs-theme";
import { DocsThemeToggle } from "./docs-theme-toggle";

function DocsShellInner({ children }: { children: React.ReactNode }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  const { websiteUrl, signupUrl } = useDocsProduct();

  return (
    <div className="min-h-screen bg-white text-slate-900 dark:bg-[#0a0a0f] dark:text-slate-100">
      <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur-md dark:border-white/10 dark:bg-[#0a0a0f]/90">
        <div className="flex h-14 items-center gap-4 px-4 lg:px-6">
          <button
            type="button"
            className="rounded-md p-2 text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-white/5 lg:hidden"
            onClick={() => setMobileOpen(true)}
            aria-label="Open menu"
          >
            <Menu className="h-5 w-5" />
          </button>

          <DocsLogo href="/docs" size="sm" />

          <div className="hidden flex-1 justify-center px-4 md:flex">
            <DocsSearchTrigger />
          </div>

          <div className="ml-auto flex items-center gap-1 sm:gap-2">
            <DocsThemeToggle />
            <a
              href={websiteUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="hidden text-sm text-slate-600 transition hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-200 sm:inline"
            >
              Website
            </a>
            <a
              href={signupUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-lg bg-brand-600 px-3 py-1.5 text-sm font-medium text-white transition hover:bg-brand-700"
            >
              Sign Up
            </a>
          </div>
        </div>

        <div className="border-t border-slate-100 px-4 py-2 dark:border-white/5 md:hidden">
          <DocsSearchTrigger />
        </div>
      </header>

      <div className="flex min-h-[calc(100vh-3.5rem)]">
        <aside className="hidden w-72 shrink-0 border-r border-slate-200 bg-slate-50 dark:border-white/10 dark:bg-[#0f0f14] lg:block xl:w-80">
          <div className="sticky top-14 flex h-[calc(100vh-3.5rem)] flex-col overflow-y-auto px-4 py-6">
            <DocsSidebar />
            <p className="mt-auto pt-8 text-xs text-slate-400 dark:text-slate-500">
              Generated by{" "}
              <Link
                href="/"
                className="text-brand-600 hover:text-brand-700 dark:text-violet-400 dark:hover:text-violet-300"
              >
                Blazly
              </Link>
            </p>
          </div>
        </aside>

        {mobileOpen && (
          <div className="fixed inset-0 z-40 lg:hidden">
            <button
              type="button"
              className="absolute inset-0 bg-slate-900/40 dark:bg-black/60"
              onClick={() => setMobileOpen(false)}
              aria-label="Close menu"
            />
            <div className="absolute left-0 top-0 flex h-full w-80 max-w-[85vw] flex-col border-r border-slate-200 bg-slate-50 shadow-xl dark:border-white/10 dark:bg-[#0f0f14]">
              <div className="flex items-center justify-between border-b border-slate-200 px-4 py-3 dark:border-white/10">
                <span className="text-sm font-semibold text-slate-900 dark:text-slate-200">
                  Documentation
                </span>
                <button
                  type="button"
                  onClick={() => setMobileOpen(false)}
                  className="rounded p-1 text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-white/5"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>
              <div className="flex-1 overflow-y-auto px-4 py-4">
                <DocsSidebar onNavigate={() => setMobileOpen(false)} />
              </div>
              <p className="border-t border-slate-200 px-4 py-3 text-xs text-slate-400 dark:border-white/10 dark:text-slate-500">
                Generated by Blazly
              </p>
            </div>
          </div>
        )}

        <main className="min-w-0 flex-1 px-4 py-8 sm:px-8 lg:px-12 lg:py-10">
          <div className="mx-auto max-w-3xl">{children}</div>
        </main>
      </div>
    </div>
  );
}

export function DocsShell({ children }: { children: React.ReactNode }) {
  return (
    <DocsThemeProvider>
      <DocsProductProvider>
        <DocsShellInner>{children}</DocsShellInner>
      </DocsProductProvider>
    </DocsThemeProvider>
  );
}
